# Generated by Django 3.0.8 on 2020-07-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.Category')),
                ('ingredients', models.ManyToManyField(blank=True, to='items.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('internal_name', models.CharField(max_length=200)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.ManyToManyField(blank=True, to='items.Ingredient')),
                ('item', models.ManyToManyField(blank=True, related_name='variants', to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('internal_name', models.CharField(max_length=200)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.ManyToManyField(blank=True, to='items.Ingredient')),
                ('item', models.ManyToManyField(blank=True, related_name='modifiers', to='items.Item')),
            ],
        ),
    ]
