# Generated by Django 3.0.7 on 2020-06-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200628_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='items.Ingredient'),
        ),
    ]
