# Generated by Django 3.0.7 on 2020-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20200628_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryvariant',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='items.Ingredient'),
        ),
    ]
