# Generated by Django 3.0.7 on 2020-06-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_categoryvariant_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('markup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredients', models.ManyToManyField(blank=True, to='items.Ingredient')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='items.Item')),
            ],
        ),
    ]
