# Generated by Django 3.0.7 on 2020-07-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20200705_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='variants', to='items.Item'),
        ),
    ]
