# Generated by Django 3.0.7 on 2020-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200705_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='modifiers', to='items.Item'),
        ),
    ]
